basePath: /api
host: localhost:8080
info:
  contact: {}
  description: This is a sample server celler server.
  title: Swagger Example API
  version: "1.0"
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: ping
      produces:
      - plain/text
      responses:
        "200":
          description: pong
          schema:
            type: string
      summary: Ping example
      tags:
      - ping
swagger: "2.0"
